<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_template.php by Valery Votintsev, codersclub.org
 *
 *      This file is automatically generate
 */

$lang = array (
	'activity_about_member'		=> 'Remaining places',//'剩余名额',
	'activity_already'		=> 'Katılım',
	'additional'			=> 'Additional',//'附加',
	'debate_opponent'		=> 'Karşı',
	'debate_square'			=> 'Taraf',
	'thread_poll'			=> 'Anketler',
	'credits'			=> 'Puan',
	'login'				=> 'Giriş',
	'active_email'			=> 'Receive E-mail',//'接收邮箱',
	'active_email_comment'		=> 'Required to receive an invitation code to E-mail Address',//'必填，用来接收邀请码的邮箱地址',
	'apitype_alipay'		=> 'AliPay',
	'apitype_tenpay'		=> 'TenPay',
	'buy_nums'			=> 'Quantity',
	'confirms'			=> 'Onayla',
	'copycode'			=> 'Copy all to clipboard',//'全部复制到剪贴板',
	'copycode_invite_succeed'	=> 'Invitation code has been copied to the clipboard',//'邀请码已经复制到剪贴板',
	'invitecode_buycode'		=> 'Obtain invitation code',//'获取邀请码',
	'invitecode_email'		=> 'We will also sent invite code to your mailbox <span class="xi1">$order[email]</span> for inspection',//'我们还将邀请码发送到了您填写的邮箱 <span class="xi1">$order[email]</span> 以备查阅',
	'invitecode_expiration'		=> 'Expiration time',//'失效时间',
	'invitecode_succeed_title'	=> 'Congratulations, you have successfully obtained invite code',//'恭喜您，成功获得邀请码',
	'money_unit'			=> 'USD',//'元',
	'need_money'			=> 'Required to pay',//'需支付',
	'reg_continue'			=> 'Continue Registration',//'继续注册',
	'trade_type'			=> 'Payment method',//'付款方式',
	'e_fontoptions'			=> '"Arial", "Verdana", "Tahoma", "Times New Roman", "Impact", "Trebuchet MS"',//'"仿宋_GB2312", "黑体", "楷体_GB2312", "宋体", "新宋体", "微软雅黑", "Trebuchet MS", "Tahoma", "Arial", "Impact", "Verdana", "Times New Roman"',
	'editor_increase'		=> 'Genişlet',
	'editor_narrow'			=> 'Daralt',
	'post_autosave_restore'		=> 'Restore',//'恢复数据',
	'post_check_length'		=> 'Kelime kontrol',
	'post_savedata'			=> 'Kaydet',
	'post_topicreset'		=> 'Temizle',
	'all'				=> 'All',//'全部',
	'faq'				=> 'SSS',
	'faq_search_nomatch'		=> 'Üzgünüz, hiçbir sonuç bulunamadı',
	'homepage'			=> 'Anasayfa',
	'keyword_faq'			=> 'Keyword &quot;<span class="xi1">$keyword</span>&quot; Help',//'关键字为“<span class="xi1">$keyword</span>”Help',
	'open'				=> 'Aç',
	'search'			=> 'Arama',
	'close'				=> 'Kapa',
	'focus_hottopics'		=> 'Önerilenler',
	'focus_show'			=> 'Göster',
	'newpm_subject'			=> 'New PM',//'新的短消息',
	'newpm_notice_info'		=> 'You have a new short message, go to see it',//'有新的短消息，快去看看吧',
	'newnotice_notice_info'		=> 'You have a new notice, go to see it',//'有新的提醒，快去看看吧',
	'footer_next'			=> 'Next post',//'下一条',
	'footer_previous'		=> 'Previous post',//'上一条',
	'login_invisible_mode'		=> 'Görünmez',
	'login_normal_mode'		=> 'Görünür',//'在线',
	'scrolltop'			=> 'To Top',//'回顶部',
	'thread_groupupgrade'		=> 'Üst grup için gereken:',
/*vot*/	'time_now'			=> '{$_G[timenow][time]} GMT{$_G[timenow][offset]}',
	'activation'			=> 'Etkinleştir',
	'admincp'			=> 'Yönetici Paneli',//'管理中心',
/*vot*/	'changestyle'			=> '',//'Change Style:',//'切换风格',
	'cloudcp'			=> 'CloudCP',//'云平台',
	'default'			=> 'Default',//'默认',
	'forum_manager'			=> 'Moderatör paneli',
	'shortcut_notice'		=> 'If you visit {$_G[setting][bbname]} frequently, Try to access to the desktop version for more convenience!',//'您经常访问 {$_G[setting][bbname]}，试试添加到桌面，访问更方便！',
	'shortcut_add'			=> 'To {$_G[setting][bbname]} desktop version',//'添加 {$_G[setting][bbname]} 到桌面',
	'go_to_mobile'			=> 'To the mobile version',//'进入手机版',
	'header_diy_mode_adv'		=> 'Advanced Mode',//'高级模式',
	'header_diy_mode_simple'	=> 'Simple mode',//'简洁模式',
	'header_qq_login_user'		=> 'QQ logged user',//'QQ 登录用户',
	'login_switch_invisible_mode'	=> 'Değiştir',
	'logout'			=> 'Çıkış',
	'my_nav'			=> 'Menü',
	'my_nav_login'			=> 'Lütfen <a href="javascript:;" class="xi2" onclick="lsSubmit()"><strong>giriş yapınız</strong></a> veya<br /><a href="member.php?mod={$_G[setting][regname]}" class="xi2 xw1">Register olunuz</a>',
	'open_diy'			=> 'DIY Panel',
	'pm_center'			=> 'Ö.M',
	'portal_block_manage'		=> 'Block Management',//'模块管理',
	'portal_manage'			=> 'Portal CP',
	'remind'			=> 'Hatırlatma',
	'setup'				=> 'Ayarlar',
	'freeze'			=> 'Frozen',//'已冻结',
	'switch_narrow'			=> 'Dar',
	'switch_wide'			=> 'Geniş',
	'switch_blind'			=> 'Enable Auxiliary Access',//'开启辅助访问',
	'task_doing'			=> 'Geçerli',
	'to_be_continue'		=> 'Continue to access the desktop computer version',//'继续访问电脑版',
	'usergroup'			=> 'Üyegrup',
	'visit_my_space'		=> 'Visit Benim Space',//'访问我的空间',
	'your_mobile_browser'		=> 'Please select ',//'请选择 ',
	'e_redo'			=> 'Tekrar',
	'e_undo'			=> 'Geri',
	'header_add_frame'		=> 'Çerçeve ekle',
	'header_add_module'		=> 'Modül ekle',
	'header_clearall'		=> 'Temizle',
	'header_clearall_desc'		=> 'Clear all layout data of current page',//'清空页面上所在DIY数据',
	'header_diy'			=> 'Özel',
	'header_diy_backup_tip'		=> 'Yardım',
	'header_diy_i_know'		=> 'Gereksiz',
	'header_diy_sample_mode'	=> 'Current is <strong>Simple mode</strong>, You can update blocks, Modify block properties and data. To use the full drag and drop mode <a href="javascript:;" onclick="spaceDiy.init();" class="xw1 xi2">Click to enter advanced mode</a>',//'当前为<strong>简洁模式</strong>，您可以更新模块，修改模块属性和数据，要使用完整的拖拽功能，<a href="javascript:;" onclick="spaceDiy.init();" class="xw1 xi2">请点击进入高级模式</a>',
	'header_export'			=> 'Dışa al',
	'header_export_desc'		=> 'Export current page layout',//'导出当前页面中所有DIY数据',
	'header_frame'			=> 'Çerçeve',
	'header_import'			=> 'Import',//'导入',
	'header_import_desc'		=> 'Import layout data into the current page',//'将DIY数据导入到当前页面',
	'header_module'			=> 'Modül',
	'header_more_actions'		=> 'More actions',//'更多操作',
	'header_perview'		=> 'Önizleme',
	'header_perview_desc'		=> 'Önizleme DIY',
	'header_restore_backup'		=> 'Geri al',
	'header_restore_backup_desc'	=> 'Geri al',
	'header_start'			=> 'Start',//'开始',
	'header_update'			=> 'Güncelle',
	'header_update_desc'		=> 'Update all blocks data in the current page',//'更新当前页面所有模块的数据',
	'save'				=> 'Kaydet',
	'style'				=> 'Stil',
	'find'				=> 'Arama ',
	'invite'			=> 'Davet',
	'invite_all_friend'		=> 'Tüm arkadaşlar',
	'invite_friend'			=> 'Arkadaş davetle ',
	'invite_my_follow'		=> 'I am follow',//'我关注的',
	'invite_orderby_friend'		=> 'Arkadaş kategori',
	'invite_orderby_name'		=> 'Arkadaş adı',
	'invite_send'			=> 'Davet Gönder',
	'invite_still_choose'		=> 'Kalanlar ',
	'selected'			=> 'Seçili',
	'unit'				=> ' ',
	'unselected'			=> 'Kalanlar',
	'imgcropper'			=> 'Crop Image',//'裁切图片',
	'imgcropper_crop'		=> 'Crop',//'裁切',
	'parse_av_tips'			=> 'If it cannot be played, please click here to open in a new window',
	'preview_footertext'		=> 'Copyright and Footer info',//'版权及页脚信息',
	'preview_highlightlink'		=> 'Highlight link',//'高亮链接',
	'preview_lighttext'		=> 'HighLight Text',//'浅色文字',
	'preview_link'			=> 'Link Text',//'链接文字',
	'preview_midtext'		=> 'Orta Text',
	'preview_msg'			=> '<a href="javascript:;" class="xi2">Crossday Discuz! Board</a> Community System (Abbreviation <strong class="xw1 xi1">Discuz!</strong>) is a PHP and MySQL system using a variety of database technologies and other high-level communication solutions.',//'<a href="javascript:;" class="lit">Crossday Discuz! Board</a> 社区系统（简称 <stong class="xw1 xi1">Discuz!</stong>）是一个采用 PHP 和 MySQL 等其他多种数据库构建的高效建站解决方案。',
	'preview_smalltext'		=> 'Small Font',//'SMALL FONT',
	'preview_text'			=> 'Plain text',//'普通文本',
	'preview_threadtext'		=> 'Preview thread',//'主题列表字体',
	'table_header'			=> 'Header',//'表头',
	'album'				=> 'Albüm',
	'article'			=> 'Makale',
	'blog'				=> 'Blog',
	'enter_content'			=> 'Anahtar kelimeler...',
	'hot_search'			=> 'Sıcak Arama',
	'search_this_forum'		=> 'Arama ',
	'thread'			=> 'Konu',
	'users'				=> 'Üye',
	'input_message1'		=> 'Toplam ',
	'input_message2'		=> 'karakter girebilirsiniz.',
	'report'			=> 'Uyar',
	'report_reason'			=> 'Neden',
	'report_reason_message'		=> "['Adverting/Spam','Illegal content','Malicious irrigation','Duplicated post','Other']",//"['广告垃圾','违规内容','恶意灌水','重复发帖','其他']",
	'report_reason_other'		=> 'Please fill in report content',//'请填写举报内容',
	'seccode'			=> 'Kod',
	'seccode_change'		=> 'Değiştir',
	'secqaa'			=> 'Güvenlik S&C',
	'at_friend'			=> '@user',//'@朋友',
	'e_at'				=> '@user',//'@朋友',
	'e_bold'			=> 'Bold',
	'e_code'			=> 'Kod',
	'e_forecolor'			=> 'Yazı Renk',
	'e_image'			=> 'Resim',
	'e_quote'			=> 'Alıntı',
	'e_url'				=> 'URL Ekle',
	'attach_forward'		=> 'Eğer yükleme {$refreshsecond} saniye içersinde başlamıyorsa,lütfen buraya tıklayın',
	'board_message'			=> 'İpuçları',
	'cancel'			=> 'İptal',
	'message_closetime'		=> 'Seconds after the window closed',//'秒后窗口关闭',
	'message_forward'		=> 'Tarayıcınız otomatik olarak yönlendiremiyorsa, lütfen buraya tıklayın',
	'message_go_back'		=> '[Geri dön]',
	'message_locationtime'		=> 'Seconds after the page jump',//'秒后页面跳转',
	'basic_situation'		=> 'Basic info',//'基本概况',
	'forum_stat'			=> 'Forum Statistics',//'版块统计',
	'manage_team'			=> 'Ekip',
	'member_list'			=> 'Üyeler',
	'mod_works'			=> 'Istatistikler',
	'stats'				=> 'Site statistics',//'站点统计',
	'trend'				=> 'Trend/Stats',//'趋势统计',
	'app_add'			=> 'Add application',
	'app_management'		=> 'Manage application',
	'submit'			=> 'Tamam',
	'e_attach_del'			=> 'Sil',
	'e_attach_mediacode'		=> 'Medya kodu ekle',
	'e_attach_url'			=> 'Dosya URL ekle',
	'readperm'			=> 'Read Permission',//'阅读权限',
	'update'			=> 'Güncelle',
	'delete'			=> 'Sil',
	'none_newthread'		=> 'Yeni mesaj bulunmuyor!',
	'author'			=> 'Yazan',
	'username'			=> 'Üye',
	'anonymous'			=> 'Anonim',
	'edit'				=> 'Edit',//'编辑',
	'thread_activity'		=> 'Etkinlikler',
	'thread_debate'			=> 'Tartışma',
	'thread_reward'			=> 'Ödüller',
	'thread_trade'			=> 'Ticaret',
	'more'				=> 'Devam',
	'publish'			=> 'Yayınla',
	'guest'				=> 'Guest',
	'upload'			=> 'Yükle',
	'e_attach_insert'		=> 'Eklemek için dosyaya tıklayın',
	'e_attach_inserturl'		=> ', &quot;attach://&quot; at the beginning of the attachment address support the download for anyone, please add carefully.',//', "attach://" 开头的附件地址支持任何人下载请谨慎添加',
	'e_img_albumlist'		=> 'Albüm Resim',
	'e_img_attach'			=> 'Resimler',
	'e_img_height'			=> 'Yükseklik',
	'e_img_insertphoto'		=> 'Eklemek için resme tıklayın',
	'e_img_inserturl'		=> 'Lütfen resim URL giriniz',
	'e_img_width'			=> 'Genişlik',
	'e_img_www'			=> 'Web Resim',
	'target_blank'			=> 'Open in a new window',//'新窗口打开',
	'return'			=> 'Geridön',
	'discuzcode'			=> 'BBKod',
	'member'			=> 'Üye',
	'panel_login'			=> 'Panel Login',
	'panel_login_password'		=> 'Şifre',
	'panel_login_username'		=> 'Üye',
	'panel_notice_login'		=> 'Yanlış şifre girdiğiniz takdirde sistem 15 dakika boyunca kilitlenecektir.',
	'select_all'			=> 'Hepsi',
	'e_at_title'			=> 'Add user name as a link',//'@好友和关注的人',
	'e_attach'			=> 'Attachment',//'附件',
	'e_attach_title'		=> 'Dosya Ekle',
	'e_audio'			=> 'Müzik',
	'e_audio_title'			=> 'Müzik Ekle',
	'e_autotypeset'			=> 'Oto',
	'e_center'			=> 'Ortala',
	'e_code_title'			=> 'Kod Ekle',
	'e_downremoteimg'		=> 'Download Image',//'下载图片',
	'e_downremoteimg_title'		=> 'Download remote images',//'下载远程图片',
	'e_flash'			=> 'Flash',
	'e_flash_title'			=> 'Flash Ekle',
	'e_font'			=> 'Font',//'字体',
	'e_fontname'			=> 'Font ad',
	'e_fontsize'			=> 'Yazı Boyut',
	'e_free'			=> 'Free Bilgi',
	'e_hide'			=> 'Gizli Bilgi',
	'e_hr_title'			=> 'Yatay çizgi',
	'e_image_title'			=> 'Resim Ekle',
	'e_italic'			=> 'Italik',
	'e_left'			=> 'Sol',
	'e_orderedlist'			=> 'Dizili Liste',
	'e_pasteword'			=> 'Paste from Word',//'Word 粘贴',
	'e_pasteword_title'		=> 'Paste content from Word',//'从 Word 粘贴内容',
	'e_quote_title'			=> 'Alıntı Ekle',
	'e_removeformat'		=> 'Format Kaldır',
	'e_right'			=> 'Sağ',
	'e_size'			=> 'Size',//'大小',
	'e_smilies'			=> 'İfadeler',
	'e_smilies_title'		=> 'İfade Ekle',
	'e_table'			=> 'Tablo Ekle',
	'e_underline'			=> 'Altçizgi',
	'e_unlink'			=> 'URL Sil',
	'e_unorderedlist'		=> 'Dizinsiz Liste',
	'e_video'			=> 'Video',//'视频',
	'e_video_title'			=> 'Video Ekle',
	'smilies'			=> 'İfadeler',
	'uid'				=> 'Üye N°',
	'recommend'			=> 'Recommend block',//'模块推送',
	'trade'				=> 'Ticaret',
	'manage'			=> 'Manage',//'管理',
	'not_enough'			=> 'Insufficient',//'不足',
	'moderate_need'			=> 'Pending',//'待审核',
	'portal'			=> 'Site',
	'reward_answer'			=> 'Cevap',
	'favorite'			=> 'Favoriler',
	'choose_please'			=> 'Seç',
	'create'			=> 'Ekle',
	'finished'			=> 'Completed',
	'ignore_all'			=> 'Hepsi İptal',
	'pass_all'			=> 'Pass all',
	'create_on'			=> 'Ekleme ',
	'activity'			=> 'Etkinlikler',
	'debate'			=> 'Tartışmalar',
	'poll'				=> 'Anketler',
	'reward'			=> 'Ödüller',
	'add'				=> 'Ekle',
	'blockdata_recommend'		=> 'Tavsiye',
	'share'				=> 'Paylaş',
	'article_push'			=> 'Makale Push',
	'doing'				=> 'Ruh halleri',
	'friends'			=> 'Arkadaşlar',
	'online_member'			=> 'Online members',//'在线成员',
	'my_space'			=> 'Üye Paneli',
	'magic'				=> 'Magic',//'道具',
	'medals'			=> 'Madalya',
	'task'				=> 'Görevler',
	'notice'			=> ' Duyuru',
	'notice_pm'			=> 'Benim PM',//'我的私信',
	'notice_mypost'			=> 'Benim Konular',//'我的帖子',
	'notice_mypost_at'		=> 'Mention to me',//'提到我的',
	'notice_mypost_post'		=> 'Konular',//'帖子',
	'notice_mypost_pcomment'	=> 'Comments',//'点评',
	'notice_mypost_activity'	=> 'Activity',//'活动',
	'notice_mypost_reward'		=> 'Rewards',//'悬赏',
	'notice_mypost_goods'		=> 'Products',//'商品',
	'notice_interactive'		=> 'Friends interaction',//'坛友互动',
	'notice_interactive_follow'	=> 'I follow',//'我关注的',
	'notice_interactive_follower'	=> 'Benim followers',//'新听众',
	'notice_interactive_poke'	=> 'Greetings',//'打招呼',
	'notice_interactive_friend'	=> 'Friends',//'好友',
	'notice_interactive_comment'	=> 'Comments',//'评论',
	'notice_interactive_wall'	=> 'Wall',//'留言',
	'notice_interactive_click'	=> 'Rates',//'挺你',
	'notice_interactive_sharenotice'	=> 'Paylaşımlar',//'分享',
	'notice_system'			=> 'System messages',//'系统提醒',
	'notice_manage'			=> 'Manage work',//'管理工作',
	'notice_app'			=> 'Application messages',//'应用提醒',
	'notice_userapp'		=> 'Application invites',//'应用邀请',
	'you'				=> 'You',//'您',
	'group_expiry_type_ext'		=> 'Extended user group',//'扩展用户组',
	'task_done'			=> 'Tamamlananlar',
	'task_failed'			=> 'Başarısız',
	'task_new'			=> 'Yeni',
	'task_admins'			=> 'Yöneticiler',
	'task_applicants'		=> 'Toplam $task[applicants] üye bu görev için başvurmuş.',
	'task_applies_full'		=> 'Başvurular dolmuştur.',//Modify
	'task_apply_condition'		=> 'Koşullar',
	'task_applyagain'		=> ' tekrar başvur',
	'task_applyagain_now'		=> 'Tekrar başvurabilirsiniz',
	'task_complete'			=> 'Tamamlanmış',
	'task_complete_condition'	=> 'Görev tamamlama koşulu',
	'task_complete_on'		=> 'Tamamlama  ',
	'task_detail'			=> 'Görev Detaylar',
	'task_endtime'			=> 'Bu görev\'in bitiş tarihi: $task[endtime], bu tarih\'ten sonra başvuramazsınız',
	'task_general_users'		=> 'Genel üyeler',
	'task_group_nopermission'	=> 'Üye grubunuzun bu görev için izni bulunmuyor.',
	'task_lose_on'			=> 'Vazgeçme  ',
	'task_numlimit'			=> 'Max başvuru',//modify
	'task_period_day'		=> 'Her $task[period] gün\'de tekrar deneyebilirsiniz.',
	'task_period_hour'		=> 'Her $task[period] saat\'te tekrar deneyebilirsiniz.',
	'task_period_month'		=> 'Her $task[period] ay\'da tekrar deneyebilirsiniz.',
	'task_period_week'		=> 'Her $periodweek hafta\'da tekrar deneyebilirsiniz.',
	'task_reapply'			=> ' tekrar dene',
	'task_reapply_now'		=> 'Tekrar deneyebilirsiniz',
	'task_relatedtask'		=> 'Ilgili görevi tamamlamalısınız',
	'task_reward'			=> 'Ödüller',
	'task_applies'			=> 'Başvurma',
	'task_nodoing'			=> 'Başladığınız görev yok, yeni görevlere bakınız',
	'task_nonew'			=> 'Yeni görev bulunmuyor, daha sonra tekrar kontrol ediniz',
	'password_security'		=> 'Şifre',
	'increase'			=> 'Increase',//'增加',
	'friend_top'			=> 'Friend Top List',//'排行榜',
	'connect_register_profile'	=> 'Create new account',//'创建新帐号',
	'connect_register_bind'		=> 'Allready have account',//'已有本站帐号',
	'connect_member_login_tip'	=> 'Welcome to {$_G[setting][bbname]} logged with QQ account',//'欢迎使用QQ帐号登录  {$_G[setting][bbname]}',
	'connect_config_newpassword_comment'	=> 'You are currently use a QQ account was bind to the site. Here you can set up individual password, Only set up an independent password site to fill in the password so the corresponding function can use it',//'你目前使用的是QQ帐号绑定本站，你可以在这里设置独立密码，只有设置了独立密码后本站需要填写密码的相应功能才可使用',
/*3.2*/	'wechat_config_newpassword_comment'	=> 'You are currently using the micro-channel account binding to the site, Here you can set separate password. Only after setting up an independent site requires a password to enter a password in order to use the corresponding function.',//'您目前使用的是微信帐号绑定本站，您可以在这里设置独立密码，只有设置了独立密码后本站需要填写密码的相应功能才可使用',
	'email'				=> 'E-mail',
	'security_question'		=> 'Yoksa, geçiniz',
	'security_question_0'		=> 'Güvenlik Sorusu',
	'security_question_1'		=> 'Anne ismi',
	'security_question_2'		=> 'Yemek ismi',
	'security_question_3'		=> 'Dede ismi',
	'security_question_4'		=> 'Şanslı sayınız',
	'security_question_5'		=> 'Sevdiğiniz yemek',
	'security_question_6'		=> 'Öğretmeninizin ismi',
	'security_question_7'		=> 'Ilk sevgilinizin ismi',
	'group_expiry_time'		=> 'Geçerlilik',
	'login_id'			=> 'Üye N°:',
	'login_password'		=> 'Şifre:',
	'login_permanent'		=> 'Hatırla?',
	'security_a'			=> 'Answer',//'答案',
	'security_q'			=> 'Güvenlik Sorusu',
	'forgotpw'			=> 'Şifremi Unuttum?',
	'image'				=> 'Resimler',
	'remote'			=> 'Remote',//'远程',
	'credit_ranking'		=> 'Kredi Sıralama',
	'auction_ranking'		=> 'Top bidding',//'竞价排行',
	'close_ranking_note'		=> 'Administrator has closed the bidding. For the time you can not continue the Ranking',//'管理员已关闭竞价,暂时无法继续上榜',
	'credit_is_not_number'		=> 'Entered value {$extcredits[$creditid][title]} is not valid',//'你所填写的{$extcredits[$creditid][title]}不是一个合法数值',
	'credit_title_error'		=> 'Entered value {$extcredits[$creditid][title]} can not be less than 1',//'你所填写的{$extcredits[$creditid][title]}不能小于1',
	'credit_title_message'		=> 'Your current {$extcredits[$creditid][title]} is: "+maxCredit+", please fill in a value less than this number',//'你的当前{$extcredits[$creditid][title]}为: "+maxCredit+",请填写一个小于该值的数字',
	'current_ranking'		=> 'Güncel Sıralama',
	'friend_need_help'		=> 'Arkadaşlara Yardım',
	'friend_num_ranking'		=> 'Arkadaş Sıralama',
	'friend_top_note'		=> 'Duyuru Listesi',
	'handsel'			=> 'Hediye',
	'handsel_bid'			=> 'Gift auction',
	'help_friend_in_top'		=> 'Arkadaş Sıralama Yardım',
	'i_ranking'			=> 'Sıralama',
	'increase_bid'			=> 'Increase bid',//'增加竞价',
	'make_persistent_efforts'	=> 'Make persistent efforts',//'再接再厉',
	'max_char_ranking'		=> 'Liste slogan için max 50 karakter giriniz ',
	'my_ranking_declaration'	=> 'Klasman Sloganım',
	'not_exceed'			=> 'Not more than you have ',//'不要超过自己的',
	'ranking_message_0'		=> 'You have not yet bid rank. Ranking yourself will greatly enhance the visibility of your home space.',//'你现在还没有上榜。让自己上榜吧,这会大大提升你的主页曝光率。',
	'ranking_message_1'		=> 'Bid {$extcredits[$creditid][title]} more,  the higher will be your home page exposure;',//'竞价{$extcredits[$creditid][title]}越多,竞价排名越靠前,你的主页曝光率也会越高；',
	'ranking_message_2'		=> 'Ranking the user is another effective browsing time, its bid {$extcredits[$creditid][title]} will be reduced by a (malicious refresh access is not deductible).',//'上榜用户的主页被别人有效浏览一次,其竞价{$extcredits[$creditid][title]}将减少1个(恶意刷新访问不扣减)。',
	'self_current_credit'		=> 'Mevcut puan',
	'self_current_friend_num'	=> 'Geçerli arkadaş sayısı',
	'top_100_update'		=> 'The following is the top 100 rank list. The data data updated every $cache_time minutes.',//'下面列出的为排行前100名, 数据每 $cache_time 分钟更新一次。',
	'your_current_bid'		=> 'Your current bid',//'自己当前的竞价',
	'top_orderby_blogs'		=> 'by number of blogs',//'按日志总数',
	'top_orderby_credits'		=> 'by number of points',//'按积分总数',
	'top_orderby_posts'		=> 'by number of posts',//'按发帖总数',
	'top_orderby_uid'		=> 'by registration time',//'按注册时间',
	'upload_pic'			=> 'Resim yükle',//'上传图片',
	'aim_album'			=> 'Upload to album:',//'上传到:',
	'default_album'			=> 'Default album',//'默认相册',
	'create_new_album'		=> 'Create a new album',//'创建新相册',
	'input_album_name'		=> 'Please enter the album name',//'请输入相册名称',
	'click_pic_to_editor'		=> 'Click the image to insert into the content',//'点击图片添加到编辑器内容中',
	'select_album'			=> 'Select album',//'选择相册',
	'upload_attach'			=> 'Upload attachment',//'上传附件',
	'filename'			=> 'File Name',//'文件名',
	'file_size'			=> 'File Size',//'文件大小',
	'click_filename_to_article'	=> 'Click the file name for add attachment into the article',//'点击文件名将附件添加到文章中',
	'connect_fill_profile_to_visit'	=> 'Please<br /><a class="xi2" href="member.php?mod=connect"><strong>Provide the account information</strong></a> or <a href="member.php?mod=connect&ac=bind" class="xi2 xw1"><strong>Bind existing account</strong></a><br />for use the Quick Navigation',//'请先<br /><a class="xi2" href="member.php?mod=connect"><strong>完善帐号信息</strong></a> 或 <a href="member.php?mod=connect&ac=bind" class="xi2 xw1"><strong>绑定已有帐号</strong></a><br />后使用快捷导航',
	'ipnoice_current'		=> 'This login location',//'本次登录位置',
	'ipnoice_last'			=> 'Last login location',//'上次登录位置',
	'ipnoice_lasttime'		=> 'Last login time',//'上次登录时间',
	'ipnoice_title'			=> 'Security reminder',//'安全提醒',
	'ipnoice_link'			=> 'Login Place is abnormal, recommended to change your password',//'登录地点异常，建议立即更改密码',
	'recharge_immediately'		=> 'Recharge Now',//'立即充值',
	'manage_grade'			=> 'Manage level',//'管理级别',
	'manager'			=> 'Administrator',//'管理员',
	'super_forummanager'		=> 'Super Moderator',//'超级版主',
	'forummanager'			=> 'Moderator',//'版主',
	'buy_usergroup'			=> 'Purchase a user group',//'购买用户组',
	'fastreply'			=> 'Quick Reply',//'快速回复',
	'return_list'			=> 'Return to the list',//'返回列表',
	'return_forum'			=> 'Return to the forum',//'返回版块',
	'temporarily_to_remind'		=> 'Temporarily to remind',//'暂不提醒',
	'myitem'			=> 'Benim',//'我的',
	'mypost'			=> 'Konular',//'帖子',

  'm_loading'       => 'Loading...',//'正在加载...',
  'm_its_all'       => 'Show all',//'已显示全部',
  'm_view_his'      => 'View historical news',//'查看历史消息',
  'm_login_user'    => 'Account number:',//'帐 号：',
  'm_login_user_ph' => 'Please enter your account',//'请输入帐户',
  'm_login_pw'      => 'Password:',//'密 码：',
  'm_login_pw_ph'   => 'Please enter your password',//'请输入密码',
  'm_login_q'       => 'Security Question:',//'安全提问：',
  'm_login_q_ph'    => 'Security Question (ignore if not set)',//'安全提问(未设置请忽略)',
  'm_login_a'       => 'Answer:',//'答 案：',
  'm_login_a_ph'    => 'Please enter the answer',//'请输入答案',
  'm_login_submit'  => 'Log in',//'登录',
  'm_login_orQQ'    => 'Or use the bound QQ account to log in',//'或使用已绑定的QQ帐号登录',
  'm_login_QQ'      => 'Log in with QQ account',//'QQ帐号登录',
  'm_login_orWX'    => 'Or log in using the bound WeChat account',//'或使用已绑定的微信帐号登录',
  'm_login_WX'      => 'Log in with WeChat account number',//'微信帐号登录',
  'm_login_reg'     => 'Register a new account',//'注册账户',
  'm_new_t'         => 'Thread',//'发帖',
  'm_new_submit'    => 'Send',//'发送',
  'm_new_subject_ph'    => 'Title (required)',//'标题（必填）',
  'm_new_memo_ph'   => 'Say a few words',//'说两句吧',
  'm_new_upload'    => 'Up to 8 images can be uploaded',//'最多可上传8张图片',
  'm_new_ttype'     => 'Thread category:',//'主题分类：',
  'm_new_tsel'      => 'Select',//'选择',
  'm_my_send_pm'    => 'Send private message',//'发送私信',
  'm_my_ntc'        => 'My reminder',//'我的提醒',
  'm_my_pm'         => 'My private messages',//'我的私信',
  'm_my_t'          => 'My threads',//'我的话题',
  'm_my_r'          => 'My replies',//'我的回复',
  'm_stickt'        => 'Sticked threads',//'置顶帖',
  'm_share'         => 'If you like this thread, please click on the icon in the upper right corner to share',//'如果喜欢这个话题，请点击右上角图标分享',
  'm_logout'        => 'Çıkış Yap',//'退出登录',

//---------------------------
// Added by Valery Votintsev

	'follow_view_follow'	=> 'I follow',//'我关注的',
	'follow_stop'		=> 'Stop follow',//'不收听',
	'follow_start'		=> 'Follow',//'收听TA',

	'e_full_screen'		=> 'Full Screen',//'全屏',
	'e_restore_size'	=> 'Restore size',//'恢复',
	'e_simple'		=> 'General Mode',//'常用',
	'e_advanced'		=> 'Advanced Mode',//'高级',

//static/space/t1/style.css
	'default_style'	=> 'Default style',//'[name]默认风格[/name]',

//---------------------------
//static/space/t2/style.css
	'nature'	=> 'Nature',//'[name]自然[/name]',

//---------------------------
//static/space/t3/style.css
	'sky'		=> 'Sky',//'[name]天空[/name]',

//---------------------------
//static/space/t4/style.css
	'cat'		=> 'Cat',//'[name]猫猫[/name]',

//---------------------------
//static/space/t5/style.css
	'courtyard'	=> 'Courtyard',//'[name]庭院[/name]',

//---------------------------
//static/space/t6/style.css
	'green_wall'	=> 'Green Wall',//'[name]绿墙[/name]',

//---------------------------
//static/space/t7/style.css
	'cowboy'	=> 'Cowboy',//'[name]牛仔[/name]',

//---------------------------
//static/space/t8/style.css
	'christmas'	=> 'Christmas',//'[name]圣诞[/name]',

//---------------------------
//static/topic/t1/style.css
	'default_skin'	=> 'Default Skin',//'[name]默认皮肤[/name]',

//---------------------------
//static/topic/t2/style.css
	'skin_2'	=> 'Skin 2',//'[name]皮肤2[/name]',

//---------------------------
//Change Language
	'change_language'	=> '',//'Change language:',
	'change_language_title'	=> 'Change language',
	'changestyle_title'	=> 'Change Style',//'切换风格',

//vot:
	'new'		=> 'New',//'全新',

	'register'	=> 'Register',//'注册',

	'or'		=> 'or',//'或者',

	'upload_selectfile'	=> 'Araştır',//'浏览',

// Google Maps
	'e_map'		=> 'Map',//'地图',
	'e_map_insert'	=> 'Insert Google Map',//'插入google地图',
	'e_map_address'	=> 'Enter address for search: ',//'地址： ',

	'processed_in'			=> 'Processed in',
	'seconds'			=> 'sec.',//'second(s)',
	'queries'			=> 'queries',

);

