<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_admincp_menu.php by Valery Votintsev, codersclub.org
 */

if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}

$lang = array
(


	'header_index'		=> 'Anasayfa',//'首页',
	'header_global'		=> 'Global',//'全局',
	'header_forum'		=> 'Forum',//'论坛',
	'header_user'		=> 'Kullanıcılar',//'用户',
	'header_topic'		=> 'Konular',//'内容',
	'header_extended'	=> 'Uzantılar',//'扩展',
	'header_plugin'		=> 'Eklentiler',//'插件',
	'header_template'	=> 'Şablonlar',
	'header_style'		=> 'Stiller',//'界面',
	'header_adv'		=> 'Reklamlar',//'广告',
	'header_tools'		=> 'Araçlar',//'工具',
	'header_uc'			=> 'UCenter',
	'header_welcome'	=> 'Hoş geldiniz',//'您好',
	'header_logout'		=> 'Oturum Kapatma',//'退出',
	'header_bbs'		=> 'Site',//'站点首页',
	'header_portal'		=> 'Portal',//'门户',
	'header_group'		=> 'Gruplar',//'群组',
	'header_safe'		=> 'Güvenlik',
	'header_founder'	=> 'Yöneticiler',//'站长',
	'header_cloudaddons'	=> 'Uygulama Merkezi',//'应用中心',


	'menu_home'						=> 'Yönetici Paneli',//'管理中心首页',
	'menu_home_clearhistorymenus'	=> 'İşlem geçmişini temizle',//'清空历史操作',

	'menu_setting_basic'		=> 'Temel Ayarlar',//'站点信息',
	'menu_setting_access'		=> 'Kayıt/Giriş',//'注册与访问控制',
	'menu_setting_customnav'	=> 'Navigasyon',//'导航栏',
	'menu_setting_styles'		=> 'Stiller',//'界面设置',
	'menu_setting_optimize'		=> 'Optimizasyon',//'优化设置',
	'menu_setting_seo'			=> 'SEO',//'SEO设置',
	'menu_setting_functions'	=> 'Site modülleri',//'站点功能',
	'menu_setting_domain'		=> 'Etki Alanları',//'域名设置',
	'menu_setting_user'			=> 'Kullanıcı İzinleri',//'用户权限',
	'menu_setting_credits'		=> 'Krediler',//'积分设置',
	'menu_setting_mail'			=> 'Posta',//'邮件设置',
	'menu_setting_sec'			=> 'Anti-spam',//'防灌水设置',
	'menu_setting_datetime'		=> 'Tarih/Saat',//'时间设置',
	'menu_setting_attachments'	=> 'Ekler',//'上传设置',
	'menu_setting_imgwater'		=> 'Filigran',//'水印设置',
	'menu_setting_uc'			=> 'UCenter ayarları',//'UCenter 设置',
	'menu_setting_uchome'		=> 'UCHome ayarlar',//'UCHome 设置',
	'menu_setting_follow'		=> 'Takip edenler',//'广播设置',
	'menu_setting_home'			=> 'Sayfa ayarları',//'空间设置',
	'menu_setting_search'		=> 'Arama Ayarları',//'搜索设置',
	'menu_setting_district'		=> 'Bölgeler',//'地区设置',
	'menu_setting_ranklist'		=> 'Rütbe Listesi',//'排行榜设置',
	'menu_setting_mobile'		=> 'Mobil Erişim',
	'menu_setting_tag'			=> 'Etiketler',//'标签管理',
	'menu_setting_antitheft'	=> 'Yakalama önleme ayarları',//'防采集设置',

	'menu_forums'				=> 'Forumlar',//'版块管理',
	'menu_forums_merge'			=> 'Forum birleştirme',//'版块合并',
	'menu_forums_threadtypes'	=> 'Konu türleri',//'主题分类',
	'menu_forums_infotypes'		=> 'Forum türleri',//'分类信息',//vot: !!! May be 'Sort IDs',//'Category(ies)',/
	'menu_forums_infooption'	=> 'Seçenek türleri',//'分类信息选项',
	'menu_grid'					=> 'Anasayfa 4 çerçeveli',//'首页四格',

	'menu_members_add'				=> 'Kullanıcı Ekle',//'添加用户',
	'menu_members_edit'				=> 'Kullanıcı Düzenle',//'用户管理',
	'menu_members_newsletter'		=> 'Haber Bültenleri',//'发送通知',
	'menu_members_mobile'			=> 'Telefon bildirimi gönder',//'发送手机通知',
	'menu_usertag'					=> 'Kullanıcı Etiketleri',//'用户标签',
	'menu_members_edit_ban_user'	=> 'Kullanıcıyı yasakla',//'禁止用户',
	'menu_members_ipban'			=> 'Ban IP',//'禁止 IP',
	'menu_members_credits'			=> 'Ödül kredileri',//'积分奖惩',
	'menu_members_profile'			=> 'Kullanıcı profili',//'用户栏目',
	'menu_members_profile_group'	=> 'Kullanıcı Grupları',//'用户栏目分组',
	'menu_members_verify_setting'	=> 'Doğrulama',//'认证设置',
	'menu_members_stat'				=> 'İstatistikler',//'资料统计',
	'menu_moderate_modmembers'		=> 'Yeni Kullanıcılar',//'审核新用户',
	'menu_profilefields'			=> 'Profil alanları',//'用户栏目定制',
	'menu_admingroups'				=> 'Yönetici Grupları',//'管理组',
	'menu_usergroups'				=> 'Kullanıcı Grupları',//'用户组',
	'menu_follow'					=> 'Takip eder',//'推荐关注',
	'menu_defaultuser'				=> 'Varsayılan kullanıcılar',//'推荐好友',

	'menu_moderate_posts'			=> 'Konu Moderasyonu',//'内容审核',
	'menu_moderate_blogs'			=> 'Bloglar',//'审核日志',
	'menu_moderate_doings'			=> 'Durumlar',//'审核记录',
	'menu_moderate_pictures'		=> 'Görüntüler',//'审核图片',
	'menu_moderate_shares'			=> 'Paylaşımlar',//'审核分享',
	'menu_moderate_comments'		=> 'Yorumlar',//'审核评论/留言',
	'menu_moderate_articles'		=> 'Makaleler',//'审核文章',
	'menu_moderate_articlecomments'	=> 'Makale Yorumları',//'审核文章评论',
	'menu_maint_threads'			=> 'İplik Yönetimi',//'主题管理',
	'menu_maint_prune'				=> 'Toplu gönderi silme',//'批量删帖',
	'menu_maint_attaches'			=> 'Ek Yönetimi',//'附件管理',
	'menu_maint_threads_group'		=> 'Orta Düzey Grup Konuları',//'群组主题管理',
	'menu_maint_prune_group'		=> 'Group Konular Toplu Silme',//'群组批量删帖',
	'menu_maint_attaches_group'		=> 'Orta Düzey Grup Ekleri',//'群组附件管理',
	'menu_setting_collection'		=> 'Favoriler',//'淘帖管理',
	'menu_posting_tags'				=> 'Etiket Yönetimi',//'标签管理',
	'menu_posting_censors'			=> 'Kötü Kelime Filtresi',//'词语过滤',
	'menu_remoderate'				=> 'İçerik moderasyonu',
	'menu_maint_report'				=> 'Kullanıcı Raporları',//'用户举报',
	'menu_threads_forumstick'		=> 'Çoklu Forum Çubuğu',//'多版块置顶',
	'menu_post_position_index'		=> 'Konular Optimizasyon',//'帖子优化',
	'menu_postcomment'				=> 'Gönderi Yorum Yönetimi',//'帖子点评管理',
	'menu_maint_doing'				=> 'Durum Yönetimi',//'记录管理',
	'menu_maint_blog'				=> 'Bloglar Yönetimi',//'日志管理',
	'menu_maint_blog_recycle_bin'	=> 'Blog Geri Dönüşüm Kutusu',//'日志回收站',
	'menu_maint_feed'				=> 'Beslemelerin Yönetimi',//'动态管理',
	'menu_maint_album'				=> 'Albüm Yönetimi',//'相册管理',
	'menu_maint_pic'				=> 'Görüntü Yönetimi',//'图片管理',
	'menu_maint_comment'			=> 'Yorumlar/Yanıtlar Yönetimi',//'评论/留言管理',
	'menu_maint_share'				=> 'Paylaşım Yönetimi',//'分享管理',

	'menu_posting_attachtypes'		=> 'Ek boyutu',//'附件类型尺寸',
	'menu_moderate_recyclebin'		=> 'Geri Dönüşüm Kutusu',//'主题回收站',
	'menu_moderate_recyclebinpost'	=> 'Konular Geri Dönüşüm Kutusu',//'回帖回收站',

	'menu_founder'					=> 'Yönetici Bilgileri',//'站点信息',
	'menu_founder_perm'				=> 'Yönetici Ekibi',//'后台管理团队',
	'menu_founder_groupperm'		=> 'Grup izinlerini düzenleme - {group}',//'编辑团队职务权限 - {group}',
	'menu_founder_permgrouplist'	=> 'İzinleri Düzenle - {perm}',//'编辑权限 - {perm}',
	'menu_founder_memberperm'		=> 'Üye izinlerini düzenleme - {username}',//'编辑团队成员 - {username}',

	'menu_patch'			=> 'Güvenlik Merkezi',//'安全中心',
	'menu_upgrade'			=> 'Çevrimiçi yükseltme',//'在线升级',
	'menu_optimizer'		=> 'Optimizer sihirbazı',//'优化大师',
	'menu_security'			=> 'Güvenlik ustası',//'安全大师',
	'menu_serversec'		=> 'Sunucu güvenliği',

	'menu_addons'			=> 'Başvuru Merkezi',//'应用中心',
	'menu_plugins'			=> 'Eklentiler',//'插件',
	'menu_tasks'			=> 'Görevler',//'站点任务',
	'menu_magics'			=> 'Sihirler',//'道具中心',
	'menu_medals'			=> 'Madalyalar',//'勋章中心',
	'menu_misc_help'		=> 'Site Yardımı',//'站点帮助',
	'menu_ec'				=> 'E-ticaret',//'电子商务',
	'menu_card'				=> 'Şarj kartı kapatma',//'充值卡密',

	'menu_styles'				=> 'Şablonlar',//'风格管理',
	'menu_styles_templates'		=> 'Şablon yönetimi',//'模板管理',
	'menu_templates_add'		=> 'Yeni şablon ekle',
	'menu_posting_smilies'		=> 'Emojiler',//'表情管理',
	'menu_click'				=> 'Derecelendirmeler',//'表态动作',
	'menu_thread_icon'			=> 'Konu simgeleri',//'主题图标',
	'menu_thread_stamp'			=> 'Konu pulları',//'主题图章',
	'menu_posting_editor'		=> 'Editör Ayarları',//'编辑器设置',
	'menu_misc_onlinelist'		=> 'Çevrimiçi simgeler',//'在线列表图标',

	'menu_misc_link'			=> 'Bağlantılar',//'友情链接',
	'menu_misc_relatedlink'		=> 'Related Links',//'关联链接',
	'memu_focus_topic'			=> 'Popüler Konular',//'站长推荐',
	'menu_adv_custom'			=> 'Site Reklamcılığı',//'站点广告',

	'menu_misc_announce'		=> 'Site Duyuruları',//'站点公告',
	'menu_tools_updatecaches'	=> 'Önbelleği güncelle',//'更新缓存',
	'menu_tools_postposition'	=> 'Gönderi konumlandırmasını optimize edin',//'高楼贴优化',
	'menu_tools_updatecounters'	=> 'Güncelleme İstatistikleri',//'更新统计',
	'menu_tools_javascript'		=> 'Javascript çağrıları',//'数据调用',
	'menu_tools_relatedtag'		=> ' Etiketler ilgili',//' 标签聚合',
	'menu_tools_creditwizard'	=> 'Puan Sihirbazı',//'积分策略向导',
	'menu_tools_fileperms'		=> 'Dosya izinleri',//'文件权限检查',
	'menu_tools_hookcheck'		=> 'Hook Kontrol',//'嵌入点校验',
	'menu_tools_filecheck'		=> 'Dosya Checksum',//'文件校验',
	'menu_tools_replacekey'		=> 'Anaktar Güncelle',
	'menu_db'					=> 'Veritabanı',//'数据库',
	'menu_postsplit'			=> 'Split Konular',//'帖子分表',
	'menu_threadsplit'			=> 'Konu Tabloları',//'主题分表',
	'menu_membersplit'			=> 'Kullanıcı tabloları',//'用户表优化',
	'menu_logs'					=> 'Log Kayıtları',//'运行记录',
	'menu_custommenu_manage'	=> 'Özel Menü',//'常用操作管理',
	'menu_misc_cron'			=> 'Cron Zamanlayıcı',//'计划任务',

	'menu_article'				=> 'Makale Yönetimi',//'文章管理',
	'menu_portalcategory'		=> 'Makale Kategorileri',//'文章分类',
	'menu_blogcategory'			=> 'Blog Kategorileri',//'日志分类',
	'menu_albumcategory'		=> 'Albüm Kategorileri',//'相册分类',
	'menu_block'				=> 'Blok Yönetimi',//'模块管理',
	'menu_blockstyle'			=> 'Blok Stilleri',//'模块样式',
	'menu_portalpermission'		=> 'Portal izinleri',//'权限列表',
	'menu_blockxml'				=> 'Üçüncü taraf blokları',//'第三方模块',
	'menu_topic'				=> 'Konu Yönetimi',//'专题管理',
	'menu_html'					=> 'HTML yönetimi',//'HTML管理',
	'menu_diytemplate'			=> 'DIY Yönetimi',//'DIY页面管理',

	'menu_group_setting'		=> 'Grup Ayarları',//'群组设置',
	'menu_group_type'			=> 'Grup Kategorileri',//'群组分类',
	'menu_group_manage'			=> 'Grup Yönetimi',//'群组管理',
	'menu_group_userperm'		=> 'Kullanıcı grubu izinleri',//'群主权限',
	'menu_group_level'			=> 'Grup Seviyeleri',//'群组等级',
	'menu_group_mod'			=> 'Grup moderasyonu',//'审核群组',

	'menu_safe_setting'			=> 'Temel Ayarlar',//'基本设置',
	'menu_safe_security'		=> 'Su geçirmez duvar',//'防水墙',
	'menu_safe_seccheck'		=> 'Kimlik Doğrulama Ayarları',//'验证设置',
	'menu_safe_accountguard'	=> 'Hesap koruması',//'帐号保镖',

	'menu_setting_manyou'		=> 'Manyou ayarları',//'Manyou 设置',
	'menu_setting_qqconnect'	=> 'QQ bağlama ayarları',//'QQ 绑定设置',

	'menu_cloud_doctor'		=> 'Teşhis Araçları',//'诊断工具',

	'admincp_title'			=> $_G['setting']['bbname'].' Yönetici Paneli',//$_G['setting']['bbname'].' 管理中心',

// Added by Valery Votintsev
	'menu_setting_language'		=> 'Diller',
);

